include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Treat these as errors instead of warnings
    avoid_print: error
    prefer_single_quotes: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 120

linter:
  rules:
    # Relaxed rules — these are too noisy for a small app
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    # File I/O exists() checks are intentional in our async storage layer
    avoid_slow_async_io: false
